server:
  port: 8080

spring:
  application:
    name: cc-system
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

ai-video:
  base-url: http://localhost:3001

ai-pipeline:
  base-url: http://localhost:3002

spring.cloud.sentinel:
  transport:
    dashboard: localhost:8858
  eager: true
